import { lazy, Suspense, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, Cube, MagnifyingGlass, ArrowClockwise, Check, Copy, DownloadSimple, FileLock, Lightning, UsersThree, X, CaretLeft, CaretRight } from '@phosphor-icons/react';
import VoxelWorld from './VoxelWorld';
import AgentsSection from './AgentsSection';
const IMDJobs = lazy(() => import('./IMDJobs'));
import { IMD, useData, read, money, count, short, time, safeLink, download, csvCell, sha256, useCopy, publishedWorkAllowed } from './lib';
import type { Market, Swarm, Seat, Publications, Publication, Artifact, Job, Envelope } from './lib';

function External({ href, children, className = '' }: { href: string | null | undefined; children: React.ReactNode; className?: string }) {
  const url = safeLink(href);
  return url ? <a className={className} href={url} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16} /></a> : null;
}
function Source({ snapshot, label }: { snapshot: { fetchedAt: string; source: string } | null; label: string }) {
  return <div className="source"><span className={snapshot ? 'dot' : 'dot muted'} />{snapshot ? <>{label} · Read {time(snapshot.fetchedAt)} <External href={snapshot.source}>Source</External></> : `${label} · Awaiting a successful read`}</div>;
}
function Notice({ error, loading, empty, retry }: { error: string; loading: boolean; empty?: boolean; retry: () => void }) {
  return error ? <div className="notice" role="alert"><p>{error}</p><button className="text-btn" onClick={retry}>Try again <ArrowClockwise /></button></div> : loading ? <div className="loading" role="status"><span /> Reading the source…</div> : empty ? <div className="notice">No records match this request.</div> : null;
}
function SectionTitle({ index, title, text, icon }: { index: string; title: string; text: string; icon: React.ReactNode }) {
  return <div className="section-title"><div className="section-icon">{icon}</div><div><div className="eyebrow">DISTRICT {index}</div><h2>{title}</h2><p>{text}</p></div></div>;
}

function MarketSection() {
  const { snapshot, error, loading, refresh: refreshData } = useData<Market>('market');
  const [sort, setSort] = useState('liquidity');
  const [selected, setSelected] = useState<string[]>([]);
  const refresh = () => { setSelected([]); refreshData(); };
  const pairs = [...(snapshot?.data.pairs ?? [])].sort((a, b) => (sort === 'volume' ? b.volume24h ?? -1 : b.liquidityUsd ?? -1) - (sort === 'volume' ? a.volume24h ?? -1 : a.liquidityUsd ?? -1));
  const deepest = [...pairs].sort((a, b) => (b.liquidityUsd ?? -1) - (a.liquidityUsd ?? -1))[0];
  const compared = pairs.filter(pair => selected.includes(pair.id));
  const exportPools = () => download('VOXEN-IMD-pools.csv', [['Read at', 'Pool', 'DEX', 'Quote', 'IMD price USD', 'Liquidity USD', '24h volume USD', '24h change %', 'Source'], ...pairs.map(p => [snapshot?.fetchedAt, p.id, p.dex, p.quote, p.priceUsd, p.liquidityUsd, p.volume24h, p.change24h, p.url])].map(row => row.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8');
  return <section id="market" className="district market-district">
    <div className="section-top"><SectionTitle index="01" title="Find your market." text="Compare the Ethereum pools trading the official IMD token." icon={<Lightning weight="fill" />} /><button className="icon-btn" aria-label="Refresh markets" disabled={loading} onClick={refresh}><ArrowClockwise /></button></div>
    <div className="market-summary"><div><span>IMD / USD</span><strong>{money(deepest?.priceUsd, true)}</strong><small>Price in the deepest reported pool</small></div><div><span>POOL LIQUIDITY</span><strong>{money(deepest?.liquidityUsd)}</strong><small>Liquidity in that pool</small></div><div><span>TRACKED POOLS</span><strong>{snapshot ? count(pairs.length) : '—'}<Cube className="small-cube" /></strong><small>Official IMD as the base token</small></div></div>
    <div className="pool-controls"><label>Order by <select value={sort} onChange={e => setSort(e.target.value)}><option value="liquidity">Liquidity</option><option value="volume">24h volume</option></select></label><span>Select up to two pools to compare</span><button className="text-btn" disabled={!pairs.length} onClick={exportPools}>Export CSV <DownloadSimple /></button></div>
    <Notice error={error} loading={loading} empty={!pairs.length} retry={refresh} />
    {pairs.length > 0 && <div className="table-scroll"><table><thead><tr><th>Compare</th><th>Market / quote</th><th>IMD price</th><th>Liquidity</th><th>24h volume</th><th>24h change</th><th><span className="sr-only">Source</span></th></tr></thead><tbody>{pairs.map(pair => <tr key={pair.id}><td><input type="checkbox" aria-label={`Compare ${pair.dex ?? 'DEX unavailable'} ${pair.quote ?? 'Unknown quote'} pool ${short(pair.id)}`} checked={selected.includes(pair.id)} disabled={selected.length === 2 && !selected.includes(pair.id)} onChange={e => setSelected(old => e.target.checked ? [...old, pair.id] : old.filter(id => id !== pair.id))} /></td><td><strong className="pool-name"><span className="pool-symbol">I</span>{pair.dex ?? 'DEX unavailable'}<small>IMD / {pair.quote ?? 'Unknown quote'}</small></strong><span className="pool-id">{short(pair.id)}</span></td><td>{money(pair.priceUsd, true)}</td><td>{money(pair.liquidityUsd)}</td><td>{money(pair.volume24h)}</td><td className={pair.change24h == null ? '' : pair.change24h < 0 ? 'negative' : 'positive'}>{pair.change24h == null ? '—' : `${pair.change24h > 0 ? '+' : ''}${pair.change24h.toFixed(2)}%`}</td><td><External href={pair.url}>Pool</External></td></tr>)}</tbody></table></div>}
    {compared.length > 0 && <div className="comparison" aria-live="polite">{compared.map(p => <div key={p.id}><span className="eyebrow">{p.dex ?? 'DEX unavailable'} · {p.quote ?? 'Unknown quote'} · {short(p.id)}</span><h3>{money(p.priceUsd, true)}</h3><p>{money(p.liquidityUsd)} liquidity · {money(p.volume24h)} volume in 24h</p><p>{p.buys24h == null ? '—' : count(p.buys24h)} buys / {p.sells24h == null ? '—' : count(p.sells24h)} sells in 24h</p></div>)}<button className="icon-btn" aria-label="Clear comparison" onClick={() => setSelected([])}><X /></button></div>}
    <Source snapshot={snapshot} label="Dexscreener" /><p className="fine-print">Reported pool data can lag. Volume is trading activity, not a return. A listed pool is not an endorsement.</p>
  </section>;
}

function SeatsSection({ swarm }: { swarm: ReturnType<typeof useData<Swarm>> }) {
  const [ids, setIds] = useState(['', '']);
  const [results, setResults] = useState<(Envelope<Seat> | null)[]>([null, null]);
  const [errors, setErrors] = useState(['', '']);
  const [busy, setBusy] = useState(false);
  const runId = useRef(0);
  const lookup = async (event: FormEvent) => {
    event.preventDefault(); const run = ++runId.current;
    setResults([null, null]); setErrors(['', '']);
    if (!ids[0].trim()) { setErrors(['Enter a seat number to look it up.', '']); return; }
    if (ids.some(id => id.trim() && (!/^\d+$/.test(id.trim()) || Number(id) > 1999))) { setErrors(['Seat numbers range from 0 to 1999.', '']); return; }
    setBusy(true);
    const responses = await Promise.allSettled(ids.map(id => id.trim() ? read<Seat>('seat', { id: String(Number(id)) }) : Promise.resolve(null)));
    if (run !== runId.current) return;
    setResults(responses.map(r => r.status === 'fulfilled' ? r.value : null));
    setErrors(responses.map(r => r.status === 'rejected' ? r.reason instanceof Error ? r.reason.message : 'Seat unavailable.' : '')); setBusy(false);
  };
  return <section id="seats" className="district seats-district"><div className="section-top"><SectionTitle index="02" title="Meet the swarm." text="Look up a seat or compare two agents through their recorded work." icon={<UsersThree weight="fill" />} /><button className="icon-btn" aria-label="Refresh swarm" disabled={swarm.loading} onClick={swarm.refresh}><ArrowClockwise /></button></div>
    <div className="swarm-strip">{[['ONLINE NOW', swarm.snapshot?.data.online], ['WORKING NOW', swarm.snapshot?.data.working], ['ACCEPTED IN 24H', swarm.snapshot?.data.accepted24h], ['ENROLLED SEATS', swarm.snapshot?.data.seats]].map(([label, value]) => <div key={String(label)}><span>{label}</span><strong>{count(value as number | null | undefined)}</strong></div>)}</div>
    <Notice error={swarm.error} loading={swarm.loading} retry={swarm.refresh} />
    <form className="seat-form" onSubmit={lookup}><label>Seat number<input aria-label="First seat number" inputMode="numeric" placeholder="Enter a seat ID" value={ids[0]} onChange={e => { ++runId.current; setBusy(false); setErrors(['', '']); setIds([e.target.value, ids[1]]); setResults([null, null]); }} maxLength={4} /></label><label>Compare with <span className="optional">optional</span><input aria-label="Second seat number" inputMode="numeric" placeholder="Add another seat" value={ids[1]} onChange={e => { ++runId.current; setBusy(false); setErrors(['', '']); setIds([ids[0], e.target.value]); setResults([null, null]); }} maxLength={4} /></label><button className="btn dark" disabled={busy}>{busy ? 'Reading…' : 'Find seats'} <MagnifyingGlass size={18} /></button></form>
    {!results.some(Boolean) && !errors.some(Boolean) && <div className="seat-empty"><div className="pixel-person"><span /><span /><span /></div><div><h3>A seat. A history. A clearer picture.</h3><p>Find an agent by its Identity.MD seat number, from 0 to 1999. Compare presence and accepted work from the same source.</p></div></div>}
    <div className="seat-results">{results.map((result, index) => errors[index] ? <div className="notice" role="alert" key={index}>{errors[index]}</div> : result ? <article className="seat-card" key={index}><div className="seat-card-top"><span className="voxel-avatar"><Cube size={32} weight="fill" /></span><div><span className="eyebrow">IDENTITY.MD</span><h3>Seat #{result.data.tokenId}</h3></div><span className={`badge ${result.data.online === true ? 'green' : ''}`}>{result.data.online === true ? 'Online' : result.data.online === false ? 'Offline' : 'Presence unavailable'}</span></div><dl><div><dt>Agent ID</dt><dd>{result.data.agentId ?? 'Unavailable'}</dd></div><div><dt>Owner</dt><dd><External href={result.data.owner ? `https://etherscan.io/address/${result.data.owner}` : null}>{short(result.data.owner)}</External>{!result.data.owner && 'Unavailable'}</dd></div><div><dt>Attempts</dt><dd>{count(result.data.attempts)}</dd></div><div><dt>Accepted</dt><dd>{count(result.data.accepted)}</dd></div><div><dt>Rejected</dt><dd>{count(result.data.rejected)}</dd></div><div><dt>Pending</dt><dd>{count(result.data.pending)}</dd></div></dl><p className="fine-print">Counts reflect the source record. Accepted work alone does not prove an agent is safe or profitable.</p><External href={`https://explorer.imd.fun/agents/${result.data.tokenId}`}>Open official record</External><Source snapshot={result} label="IMD API" /></article> : null)}</div>
    <Source snapshot={swarm.snapshot} label="IMD network" />
  </section>;
}

function PublicationSection({ onVerify }: { onVerify: (file: Artifact, source: string) => void }) {
  const [draft, setDraft] = useState(''); const [query, setQuery] = useState(''); const [type, setType] = useState('all'); const [page, setPage] = useState(1);
  const { snapshot, error, loading, refresh } = useData<Publications>('publications', { q: query, type, page: String(page) });
  const visibleItems = snapshot?.data.items.filter(publishedWorkAllowed) ?? [];
  const [detail, setDetail] = useState<{ id: string; files: Artifact[]; error: string; loading: boolean; source: string } | null>(null);
  const request = useRef(0);
  const inspect = async (publication: Publication) => {
    const current = ++request.current;
    setDetail({ id: publication.id, files: [], loading: true, error: '', source: '' });
    if (publication.files.length > 0 || !publication.jobId) { setDetail({ id: publication.id, files: publication.files, loading: false, error: '', source: snapshot?.source ?? 'https://api.imd.fun/publications' }); return; }
    try { const response = await read<Job>('job', { id: publication.jobId }); if (request.current === current) setDetail({ id: publication.id, files: response.data.files, loading: false, error: '', source: response.source }); }
    catch (reason) { if (request.current === current) setDetail({ id: publication.id, files: [], loading: false, error: reason instanceof Error ? reason.message : 'File records unavailable.', source: '' }); }
  };
  return <section id="publications" className="district publication-district"><div className="section-top"><SectionTitle index="03" title="See what gets built." text="Browse work published by the IMD network, with links to its original records." icon={<Cube weight="fill" />} /><button className="icon-btn" aria-label="Refresh publications" disabled={loading} onClick={refresh}><ArrowClockwise /></button></div>
    <div className="publication-controls"><form onSubmit={e => { e.preventDefault(); ++request.current; setQuery(draft.trim()); setPage(1); setDetail(null); }}><MagnifyingGlass /><input aria-label="Search published work" placeholder="Search published work…" value={draft} onChange={e => setDraft(e.target.value)} maxLength={200} /><button type="submit" className="text-btn">Search <ArrowRight /></button></form><label className="sr-only" htmlFor="publication-type">Type of work</label><select id="publication-type" value={type} onChange={e => { ++request.current; setType(e.target.value); setPage(1); setDetail(null); }}>{['all', 'code', 'research', 'media', 'sites', 'contracts', 'audits', 'tokens'].map(value => <option key={value} value={value}>{value === 'all' ? 'All work' : value[0].toUpperCase() + value.slice(1)}</option>)}</select></div>
    <Notice error={error} loading={loading} empty={!!snapshot && visibleItems.length === 0} retry={refresh} />
    <div className="publication-grid">{visibleItems.map((item, index) => <article className="publication-card" key={item.id}><div className="pub-meta"><span className="pub-number">{String((page - 1) * 12 + index + 1).padStart(2, '0')}</span><span className="badge">{item.type ?? 'Published work'}</span><span className="pub-date">{item.deliveredAt ? new Date(item.deliveredAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' }) : 'Date unavailable'}</span></div><h3>{item.objective.length > 160 ? `${item.objective.slice(0, 160).trim()}…` : item.objective}</h3>{item.objective.length > 160 && <details className="full-brief"><summary>Read full brief</summary><p>{item.objective}</p></details>}<div className="pub-links"><External href={item.repoUrl}>Repository</External><External href={item.siteUrl}>Website</External>{item.jobId && <External href={`https://explorer.imd.fun/jobs/${item.jobId}`}>Record</External>}</div><div className="pub-footer"><span>{item.state ?? 'Status unavailable'}</span><button className="text-btn" onClick={() => void inspect(item)}>File records <ArrowRight /></button></div>{detail?.id === item.id && <div className="artifact-list" aria-live="polite">{detail.loading ? <p>Reading file records…</p> : detail.error ? <p role="alert">{detail.error}</p> : detail.files.length === 0 ? <p>No downloadable artifact is listed for this record.</p> : detail.files.map((file, fileIndex) => <div key={`${file.hash}-${fileIndex}`}><span>{file.name ?? 'Unnamed file'}<small>{file.bytes == null ? 'Size unavailable' : `${count(file.bytes)} bytes`} · {file.hash ? 'SHA-256' : 'Fingerprint unavailable'}</small></span><External href={file.url}>Download</External><button className="text-btn" disabled={!file.hash} onClick={() => onVerify(file, detail.source)}>Verify <FileLock /></button></div>)}</div>}</article>)}</div>
    {snapshot && <div className="pagination"><span>{count(snapshot.data.count)} source records · Page {page} of {snapshot.data.totalPages}</span><div><button className="icon-btn" aria-label="Previous page" disabled={page <= 1 || loading} onClick={() => { ++request.current; setPage(p => p - 1); setDetail(null); }}><CaretLeft /></button><button className="icon-btn" aria-label="Next page" disabled={page >= snapshot.data.totalPages || loading} onClick={() => { ++request.current; setPage(p => p + 1); setDetail(null); }}><CaretRight /></button></div></div>}
    <Source snapshot={snapshot} label="IMD publications" /><p className="fine-print">This view shows Ethereum and off-chain work; other-chain and illustrative records are excluded. Page totals belong to the source index. External sites belong to their creators.</p>
  </section>;
}

function IntegritySection({ expected, setExpected, artifact, clear }: { expected: string; setExpected: (value: string) => void; artifact: { file: Artifact; source: string } | null; clear: () => void }) {
  const [fileName, setFileName] = useState(''); const [digest, setDigest] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const sequence = useRef(0); const { copied, copy } = useCopy();
  const fileInput = useRef<HTMLInputElement>(null);
  const hashFile = async (file: File | undefined) => { const id = ++sequence.current; setDigest(''); setError(''); setFileName(file?.name ?? ''); if (!file) { setBusy(false); return; } setBusy(true); try { const hash = await sha256(file); if (id === sequence.current) setDigest(hash); } catch (reason) { if (id === sequence.current) setError(reason instanceof Error ? reason.message : 'This file could not be read.'); } finally { if (id === sequence.current) setBusy(false); } };
  const normalized = expected.trim().toLowerCase(); const validExpected = /^[a-f0-9]{64}$/.test(normalized); const matched = digest && validExpected && digest === normalized;
  return <section id="integrity" className="district integrity-district"><div className="integrity-intro"><span className="integrity-cube"><FileLock size={42} weight="duotone" /></span><div className="eyebrow">DISTRICT 04</div><h2>The file you wanted.<br />Byte for byte.</h2><p>Check a downloaded artifact against its published fingerprint. Your file stays on your device.</p><a className="text-btn" href="https://imd.fun/docs/#bundles-and-artifacts" target="_blank" rel="noopener noreferrer">How IMD identifies artifacts <ArrowUpRight /></a></div><div className="integrity-tool">
    {artifact && <div className="chosen-artifact"><div><strong>{artifact.file.name ?? 'Unnamed file'}</strong><External href={artifact.source}>Official file record</External></div><button className="icon-btn" aria-label="Clear selected artifact" onClick={clear}><X /></button></div>}
    <label className="file-drop" htmlFor="artifact-file"><Cube size={32} /><strong>{fileName || 'Choose a file to check'}</strong><span>{busy ? 'Calculating fingerprint…' : 'Any file type · Up to 64 MB · Kept on your device'}</span></label><input ref={fileInput} className="file-input" id="artifact-file" type="file" aria-label="Choose artifact file" onChange={e => void hashFile(e.target.files?.[0])} />
    <label className="hash-label">Expected SHA-256<input aria-label="Expected SHA-256" value={expected} maxLength={64} onChange={e => setExpected(e.target.value)} placeholder="Paste the 64-character published fingerprint" spellCheck={false} /></label>
    {expected && !validExpected && <p className="validation" role="alert">Enter exactly 64 hexadecimal characters.</p>}
    {error && <p className="validation" role="alert">{error}</p>}
    {digest && <div className="digest-result" aria-live="polite"><span>YOUR FILE'S SHA-256</span><code>{digest}</code><div><button className="text-btn" onClick={() => void copy(digest)}>{copied === digest ? 'Copied' : copied === 'failed' ? 'Copy unavailable' : 'Copy fingerprint'} <Copy /></button><button className="text-btn" onClick={() => download('VOXEN-file-verification.json', JSON.stringify({ file: fileName, algorithm: 'SHA-256', actual: digest, expected: validExpected ? normalized : null, match: validExpected ? !!matched : null, source: artifact?.source ?? null, checkedAt: new Date().toISOString() }, null, 2), 'application/json')}>Save result <DownloadSimple /></button></div>{validExpected && <p className={`hash-status ${matched ? 'match' : 'mismatch'}`}>{matched ? <><Check /> Match — the file bytes agree.</> : <><X /> Mismatch — the file bytes differ.</>}</p>}</div>}
    <p className="fine-print">A matching fingerprint confirms the bytes. It does not establish that a file is safe to open.</p>
  </div></section>;
}

export default function App() {
  const swarm = useData<Swarm>('swarm'); const [expected, setExpected] = useState(''); const [artifact, setArtifact] = useState<{ file: Artifact; source: string } | null>(null); const { copied, copy } = useCopy();
  const selectArtifact = (file: Artifact, source: string) => { if (!file.hash) return; setExpected(file.hash); setArtifact({ file, source }); document.getElementById('integrity')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }); };
  return <><a href="#main" className="skip-link">Skip to content</a><header className="header"><a href="#" className="brand" aria-label="VOXEN IMD home"><img src="/logo.svg" alt="" /><span>VOXEN<span className="brand-imd">IMD</span></span></a><nav aria-label="Main navigation"><a href="#market">Markets</a><a href="#agents">Agents</a><a href="#imd-jobs">IMD jobs</a><a href="#publications">Published work</a></nav><a className="header-action" href="#integrity">Verify a file <ArrowUpRight size={18} /></a></header>
    <main id="main"><section className="hero"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span className="little-square" />A WORLD OF USEFUL CONNECTIONS</div><h1>Big ideas.<br />Small blocks.<br /><span>Real utility.</span></h1><p>Your own vantage point on IMD. Compare markets, run observation reports, and send research jobs to the network.</p><div className="hero-actions"><a className="btn violet" href="#market">Enter the world <ArrowRight size={20} /></a><a className="text-btn" href="#publications">Discover the work <ArrowUpRight size={18} /></a></div><div className="hero-bottom"><span className="hero-stat"><span className={swarm.snapshot ? 'dot' : 'dot muted'} />{swarm.snapshot?.data.online != null ? `${count(swarm.snapshot.data.online)} agents online at last read` : swarm.loading ? 'Reading network presence…' : 'Network presence unavailable'}</span><span>Ethereum / IMD</span></div></div><div className="hero-art"><div className="art-tag">EXPLORE EVERY DISTRICT <ArrowUpRight size={16} /></div><VoxelWorld /><div className="coordinate">40° VOXEL VIEW / CONNECTED UTILITIES</div></div></section>
    <div className="district-nav"><span>CHOOSE YOUR DISTRICT</span>{[['01', 'market', 'Markets'], ['02', 'seats', 'Swarm seats'], ['03', 'publications', 'Published work'], ['04', 'integrity', 'File integrity'], ['05', 'agents', 'Agent workspace'], ['06', 'imd-jobs', 'IMD jobs']].map(([index, id, label]) => <a href={`#${id}`} key={id}><small>{index}</small>{label}<ArrowUpRight size={16} /></a>)}</div>
    <div className="content"><AgentsSection /><Suspense fallback={<div className="loading" role="status">Opening IMD jobs…</div>}><IMDJobs /></Suspense><MarketSection /><SeatsSection swarm={swarm} /><PublicationSection onVerify={selectArtifact} /><IntegritySection expected={expected} setExpected={value => { setExpected(value); setArtifact(null); }} artifact={artifact} clear={() => { setArtifact(null); setExpected(''); }} /></div>
    </main><footer className="footer"><div className="footer-top"><a href="#" className="brand"><img src="/logo.svg" alt="" /><span>VOXEN<span className="brand-imd">IMD</span></span></a><p>A small-block world.<br />A bigger view of IMD.</p><div><External href="https://imd.fun">IMD network</External><External href="https://imd.fun/docs/">Network documentation</External><External href="https://github.com/x80zAI/voxen-imd">Source code</External></div></div><div className="contract-row"><span>OFFICIAL IMD / ETHEREUM</span><code>{IMD}</code><button className="text-btn" onClick={() => void copy(IMD)}>{copied === IMD ? 'Copied' : copied === 'failed' ? 'Copy unavailable' : 'Copy'} <Copy /></button><External href={`https://etherscan.io/token/${IMD}`}>Etherscan</External></div><div className="footer-bottom"><span>© {new Date().getFullYear()} VOXEN IMD</span><p>Independent tools for IMD. Not affiliated with the official IMD team.</p><a href="#">Back to the top ↑</a></div></footer></>;
}
